version: "3.7"

services:
  database:
    container_name: postgres_service
    image: postgres:11.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./tmp/postgres:/data/postgres
    ports:
      - "5432:5432"
